import { StyleSheet } from 'react-native';
import { colors } from '../../shared/theme/tokens';
export const hs = StyleSheet.create({
  root: { flex: 1, minHeight: 0 },
  content: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 28,
    gap: 16,
    width: '100%',
    maxWidth: 480,
    alignSelf: 'center',
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  // 작성자: 고수연 — 수치 카드 줄. 기록일 줄은 예전 기록일 때만 생기므로 카드 높이가
  // 서로 달라진다. stretch 로 한 줄 안에서 높이를 맞춘다.
  metricRow: { flexDirection: 'row', alignItems: 'stretch', gap: 10 },
  between: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  title: { fontSize: 23, fontWeight: '800', color: colors.text },
  section: { fontSize: 15, fontWeight: '700', color: colors.text },
  text: { fontSize: 13, lineHeight: 20, color: colors.text },
  muted: { fontSize: 11, lineHeight: 17, color: colors.textMuted },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.line,
    boxShadow: '0 5px 18px rgba(15,69,51,0.07)',
  },
  pill: {
    minHeight: 40,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 22,
    backgroundColor: '#E8F2ED',
    justifyContent: 'center',
    alignItems: 'center',
  },
  active: { backgroundColor: colors.primary },
  pillText: { fontSize: 12, fontWeight: '700', color: colors.primaryDark },
  white: { color: '#FFFFFF' },
  metric: {
    flex: 1,
    minWidth: 0,
    padding: 16,
    borderRadius: 24,
    backgroundColor: colors.surface,
    gap: 12,
    borderWidth: 1,
    borderColor: '#EDF4F1',
    boxShadow: '0 5px 20px rgba(33,83,67,0.035)',
  },
  metricIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricLabel: {
    fontSize: 11,
    color: '#77918F',
    fontWeight: '600',
    flexShrink: 1,
    textAlign: 'right',
  },
  metricUnit: { fontSize: 11, color: '#93A6A3', fontWeight: '500' },
  // 작성자: 고수연 — 숫자와 단위를 한 덩어리로 묶는다. '7시간 30분'이 두 쌍으로 붙는다.
  metricAmount: {
    flexDirection: 'row' as const,
    alignItems: 'baseline' as const,
    gap: 2,
  },
  metricDate: { fontSize: 9, color: '#A0B0AD', letterSpacing: 0.2 },
  syncNotice: {
    fontSize: 11,
    lineHeight: 17,
    color: '#72948E',
    paddingHorizontal: 4,
  },
  value: { fontSize: 28, fontWeight: '800', color: colors.primaryDark },
  error: { fontSize: 12, lineHeight: 18, color: colors.danger },
  input: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 18,
    padding: 14,
    fontSize: 16,
    color: colors.text,
    backgroundColor: '#FFFFFF',
    minHeight: 48,
  },
  field: { gap: 7, flex: 1 },
  spacer: { flex: 1 },
  back: {
    minWidth: 36,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backText: { fontSize: 30, color: colors.text },
});
